version: '3.7'

services:
  app:
    build: .
    env_file: .env
    ports: 
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "/app/bin/migrate up && /app/bin/api"]

  db: 
    image: postgres:alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
